name: build and push

on:
  push:
    branches: ['main']
    tags:
      - 'v*'
  pull_request:
    branches: ['main']

env:
  build_number: $(date +%y.%m).${{github.run_number}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout git'
        uses: actions/checkout@v3
      - name: 'setup nodejs'
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: npm install and build
        run: |
          npm install
          npm run build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/armin168/auth-service:${{env.DAY_OF_WEEK}}
