name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
      - run: npm install
      - run: npm run build
      - run: npm test
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ani168.authservice:$(date +%s)

      - name: Push Docker GCR
        uses: RaccoonDev/push-docker-gcr@v1
        with:
          # Google Container Registry Host
          gcr_host: asia.gcr.io
          # Docker Image Name
          image_name: ani168.authservice
          # Docker Image Tag
          image_tag: $(date +%s)
